import { inter, josefin_sans, karla, libre_franklin, open_sans, poppins } from "@/lib/fonts"
import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} ${poppins.variable} ${open_sans.variable} ${libre_franklin.variable} ${karla.variable} ${josefin_sans.variable}`}
			>
				{children}
			</body>
		</html>
	)
}
