import type { Metadata } from "next"
import "./globals.css"
import { inter, open_sans, poppins } from "@/lib/fonts"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${poppins.variable} ${open_sans.variable}`}>
				{children}
			</body>
		</html>
	)
}
